Fix possible snprintf truncation
There were issues compiling due to snprintf possibly truncating strings.

src/uclient.c:170:50: error: '%s' directive output may be truncated writing up to 1023 bytes into a region of size 1007 [-Werror=format-truncation=]
   snprintf(extra_tags, BUFSIZ, "?additional_tags=%s", config.tags);
                                                  ^~   ~~~~~~~~~~~

src/uclient.c:170:3: note: 'snprintf' output between 18 and 1041 bytes into a destination of size 1024
   snprintf(extra_tags, BUFSIZ, "?additional_tags=%s", config.tags);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~